---
#- hosts: linux
#  become: yes
#  become_user: root
#  roles:
#     - ansible-role-dftest


#  tasks:
#    - name: test connection
#      ping:


- hosts: windows
  remote_user: davemus
  roles:
    -  ansible-role-windaz-reboot
      


